### ISSUE TITLE
are both fitsio and astropy.io.fits necessary here?

### ISSUE THREAD

**Issue by aakepley** [GBTSpectroscopy/gbtpipe#13]
https://github.com/GBTSpectroscopy/gbtpipe/blob/c7a2cfb0aa71713794372e67d14d2863fc47393e/gbtpipe/MappingPipeline.py#L29

**Comment by low-sky** [comment]
Sort of.  `fitsio` is built into the NRAO software for `gbt-pipeline`.  I looked into changing it over but the APIs are different so we can't just do a `import astropy.io.fits as fitsio` in the relevant scripts.  It can be altered but it will require work, but other things are more pressing.

**Comment by aakepley** [comment]
Thanks for the explanation. I'm going to close this as issue since it doesn't seem to be particularly pressing.
